version: '3'
services:
  server-service:
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3000
  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - 3002:80
    depends_on:
      - server-service